# Generated by Django 6.0.4 on 2026-07-25 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_options_product_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='box_price',
            field=models.PositiveIntegerField(blank=True, help_text="1 qadoq (24 dona) narxi. Bo'sh qoldirilsa, mahsulot qadoqlab sotilmaydi.", null=True, verbose_name="Qadoq narxi (so'm)"),
        ),
    ]
