# Generated by Django 6.0.4 on 2026-07-25 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_box_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='box_price',
            field=models.PositiveIntegerField(blank=True, help_text="Qadoqlab sotilganda 1 donaning narxi (butun qadoq narxi emas). Bo'sh qoldirilsa, mahsulot qadoqlab sotilmaydi.", null=True, verbose_name="Qadoqdagi 1 dona narxi (so'm)"),
        ),
    ]
