# Generated by Django 6.0.4 on 2026-07-18 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('full_name', models.CharField(blank=True, max_length=200, verbose_name='Ismi')),
                ('username', models.CharField(blank=True, max_length=100, verbose_name='Username')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon raqami')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Ro'yxatdan o'tgan vaqti")),
            ],
            options={
                'verbose_name': 'Bot foydalanuvchisi',
                'verbose_name_plural': 'Bot foydalanuvchilari',
                'ordering': ['-created_at'],
            },
        ),
    ]
